### ISSUE TITLE
Add/Remove Listeners on Show/Hide

### ISSUE THREAD

**Issue by ybot1122** [jaredreich/notie.js#29]
Currently, the script will add event handlers on the window's resize event. It is a lot of event handlers, and even worse is that they persist regardless of whether or not the user has actually implemented the notification type.

My proposal is to only add the respective listener when the notification is showing, and remove the listener once the notification is hidden.

if you think this is a reasonable change, I'll be more than happy to raise a PR. Thanks!

**Comment by connorjburton** [comment]
Hey, I have a PR for this #25 - I forgot to stop listening to resize however.

**Comment by jaredreich** [comment]
I think what @connorjburton already PR'd is good and solves this in a different way with the debounce function added to each listener. This the fact that there are multiple listeners is okay because now they're running at the control of the debounce. The problem with having listeners on a specific alert type only if it's showing is what if the screen size is changed while the alerts are all hidden, there will be no listeners to update the font size in the background, so if the user triggers another alert, the font size will be wrong!
