### ISSUE TITLE
Allow overriding colors/font in a .css file rather than in JS

### ISSUE THREAD

**Issue by dbkaplun** [jaredreich/notie.js#3]

**Comment by jaredreich** [comment]
Hi Dan thanks for posting.
The font isn't set anywhere in notie.js - it automatically uses the default font or whichever font you've set on the HTML body.
Just curious, what benefits are there to changing the colors in a .css file rather than setting it once in the .js file? The intent was to only have to include one file (notie.js) instead of two (notie.js + notie.css).
Please feel to fork and modify as you like but not sure if this should be merged to master.
Thanks!

**Comment by OscarGalindo** [comment]
One file doesn't mean it's better, a js file with the functionality and a css file with the style i think it's better

**Comment by jaredreich** [comment]
Ok I understand the feedback thank you. I'll set id's to the all the necessary elements, then they can be overridden and styled with a separate .css file. Thanks.
